spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 1
    preferIpAddress: true
    instance-id: spring-cloud-eureka-client-${random.value}
    
logging:
  level:
    root: DEBUG