spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:${eureka-default-zone}}
  instance:
#    lease-expiration-duration-in-seconds: 5
#    lease-renewal-interval-in-seconds: 1
    preferIpAddress: true
    instance-id: spring-cloud-eureka-client-${random.value}
    prefer-ip-address: true
    
logging:
  level:
    root: DEBUG
    
security:
  oauth2:
    resource:
      jwt:        key-value: 
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu4Eazef1o04iZHPLZack
          nHQX1ECxLWUn5WHc937ypWlkWZHmTZnQWqS7mySooeJv+gKuiU3xr3jgzLl8LYAR
          y1N77Rw6bvx4CKkgDK0G6SZExYt1Qc/Jq5GEmma0ob7S8hqCwFirI0+di83OaEHM
          3qbGrNlsaGmfI8pWJG3CZMKqoAJhsz6f7TicXI8Wg+nbQI+lh7TFAWDIGUc/lxiO
          NvRTeCfHvUmS0ip3XtPnkGGGtFcaa5PBVQ24EXjI63M8kCWW4wYMPJPa+idKaXrR
          vML+cc6orfaJUhUqg8DpCJjccOpwyGfOxlSm09I7rF0RrejNS0R17jszZTiCkLqw
          VwIDAQAB
          -----END PUBLIC KEY-----
